services:
  - type: web
    name: resumai-api-gateway
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resumai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: resumai-db
    plan: free

