"""
ATS Exporter Service
Provides real-time ATS benchmark auditing, keyword density scoring, and
server-side generation of ATS-compliant single-column DOCX and PDF documents.
"""

import io
import re
import html
from typing import Dict, List, Any
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY


def clean_text(text: str) -> str:
    """Unescapes HTML entities, strips leading bullet symbols (▍, •, -, *), and trims whitespace."""
    if not text:
        return ""
    cleaned = html.unescape(str(text))
    cleaned = re.sub(r'^[•\-*|\▍\s]+', '', cleaned).strip()
    return cleaned


def is_header_duplicate_py(bullet_text: str) -> bool:
    """Checks if bullet text is a duplicate of a role/experience header line."""
    if not bullet_text:
        return True
    c = clean_text(bullet_text).lower()
    if "|" in c and ("present" in c or re.search(r"\b20\d\d\b", c)):
        return True
    return False


def audit_resume_ats(resume_data: Dict[str, Any], job_description: str = "") -> Dict[str, Any]:
    """
    Evaluates a resume against strict ATS compliance rules and target job description keywords.
    """
    contact_score = 0
    structure_score = 0
    format_score = 20  # Single column generated by engine guarantees formatting safety
    keyword_score = 0
    xyz_density_score = 0
    
    warnings = []
    missing_keywords = []
    recommendations = []

    # 1. Contact Info Audit (Max 20 pts)
    name = resume_data.get("name", "").strip()
    email = resume_data.get("email", "").strip()
    phone = resume_data.get("phone", "").strip()
    location = resume_data.get("location", "").strip()
    linkedin = resume_data.get("linkedin", "").strip()

    if name:
        contact_score += 5
    else:
        warnings.append("Missing full name header.")

    if email and "@" in email:
        contact_score += 5
    else:
        warnings.append("Missing or invalid email address.")

    if phone:
        contact_score += 5
    else:
        warnings.append("Missing contact phone number.")

    if location:
        contact_score += 3
    else:
        recommendations.append("Add location (City, State/Country) for ATS location filtering.")

    if linkedin:
        contact_score += 2
    else:
        recommendations.append("Include a polished LinkedIn profile link.")

    # 2. Structural Audit (Max 20 pts)
    experiences = resume_data.get("experiences", [])
    skills = resume_data.get("skills", [])
    education = resume_data.get("education", [])
    summary = resume_data.get("summary", "")

    if experiences and len(experiences) > 0:
        structure_score += 8
    else:
        warnings.append("No Work Experience section detected.")

    if skills and len(skills) > 0:
        structure_score += 5
    else:
        warnings.append("No Skills section detected.")

    if education and len(education) > 0:
        structure_score += 4
    else:
        warnings.append("No Education section detected.")

    if summary:
        structure_score += 3

    # 3. Google XYZ Formula & Metric Density (Max 15 pts)
    total_bullets = 0
    xyz_bullets = 0
    quantified_bullets = 0

    metric_regex = re.compile(r'\d+%|\$\d+|\d+\+|\b\d+\b')
    xyz_verbs_regex = re.compile(r'^(Accomplished|Increased|Decreased|Engineered|Spearheaded|Reduced|Architected|Delivered|Generated|Optimized|Accelerated|Led|Built|Implemented|Scaled)', re.IGNORECASE)

    for exp in experiences:
        bullets = exp.get("bullets", [])
        if isinstance(bullets, str):
            bullets = [b.strip() for b in bullets.split("\n") if b.strip()]
        
        for b in bullets:
            total_bullets += 1
            if metric_regex.search(b):
                quantified_bullets += 1
            if xyz_verbs_regex.search(b.strip()):
                xyz_bullets += 1

    if total_bullets > 0:
        quant_ratio = quantified_bullets / total_bullets
        xyz_ratio = xyz_bullets / total_bullets
        xyz_density_score = int((quant_ratio * 10) + (xyz_ratio * 5))
        xyz_density_score = min(15, xyz_density_score)

        if quant_ratio < 0.5:
            recommendations.append(f"Only {int(quant_ratio*100)}% of experience bullets contain numbers/metrics. Target at least 60% with Google XYZ formula.")
    else:
        recommendations.append("Add bullet points with metrics [X], outcome [Y], and action [Z] to your experience items.")

    # 4. Keyword Alignment Audit (Max 25 pts)
    if job_description:
        # Extract keywords from JD
        words = re.findall(r'\b[a-zA-Z]{3,}\b', job_description.lower())
        stopwords = {"and", "the", "for", "with", "that", "this", "from", "you", "your", "are", "have", "will", "our", "team", "work", "role", "looking", "must", "able", "skills", "experience", "years", "working"}
        keywords = [w for w in words if w not in stopwords and len(w) > 3]
        
        from collections import Counter
        top_jd_keywords = [item[0] for item in Counter(keywords).most_common(20)]

        # Search in resume content
        resume_text_corpus = (
            summary + " " +
            " ".join(skills) + " " +
            " ".join([f"{e.get('title','')} {e.get('company','')} {e.get('bullets','')}" for e in experiences])
        ).lower()

        matched_count = 0
        for kw in top_jd_keywords:
            if kw in resume_text_corpus:
                matched_count += 1
            else:
                missing_keywords.append(kw)

        if top_jd_keywords:
            match_ratio = matched_count / len(top_jd_keywords)
            keyword_score = int(match_ratio * 25)
        else:
            keyword_score = 20
    else:
        keyword_score = 20  # Neutral score if no JD provided

    total_score = contact_score + structure_score + format_score + keyword_score + xyz_density_score

    return {
        "ats_score": total_score,
        "score_breakdown": {
            "contact_information": {"score": contact_score, "max": 20},
            "structural_completeness": {"score": structure_score, "max": 20},
            "formatting_safety": {"score": format_score, "max": 20},
            "keyword_alignment": {"score": keyword_score, "max": 25},
            "google_xyz_metric_density": {"score": xyz_density_score, "max": 15},
        },
        "warnings": warnings,
        "missing_keywords": missing_keywords[:10],
        "recommendations": recommendations,
        "is_ats_compliant": total_score >= 80,
    }


def generate_docx(resume_data: Dict[str, Any]) -> bytes:
    """
    Generates a single-column ATS-optimized DOCX file tailored to the selected style format.
    """
    style_id = resume_data.get("style", "classic")

    # Define color palettes (R, G, B) based on style
    palettes = {
        "classic": (RGBColor(0x1E, 0x29, 0x3B), RGBColor(0x47, 0x55, 0x69)),
        "modern_executive": (RGBColor(0x1E, 0x3A, 0x8A), RGBColor(0x25, 0x63, 0xEB)),
        "warm_modern": (RGBColor(0x0D, 0x94, 0x88), RGBColor(0xD9, 0x77, 0x06)),
        "minimalist": (RGBColor(0x02, 0x84, 0xC7), RGBColor(0x47, 0x55, 0x69)),
        "leadership": (RGBColor(0x4F, 0x46, 0xE5), RGBColor(0x47, 0x55, 0x69)),
        "creative": (RGBColor(0x05, 0x96, 0x69), RGBColor(0x0D, 0x94, 0x88))
    }

    primary_color, secondary_color = palettes.get(style_id, palettes["classic"])

    doc = docx.Document()

    # Standard margins
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

    # Base font
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(10)
    style.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    # 1. Header (Name & Contact)
    p_name = doc.add_paragraph()
    p_name.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run_name = p_name.add_run(resume_data.get("name", "CAREER PROFESSIONAL").upper())
    run_name.font.size = Pt(20)
    run_name.font.bold = True
    run_name.font.color.rgb = primary_color

    contact_parts = []
    if resume_data.get("phone"):
        contact_parts.append(resume_data["phone"])
    if resume_data.get("email"):
        contact_parts.append(resume_data["email"])
    if resume_data.get("location"):
        contact_parts.append(resume_data["location"])
    if resume_data.get("linkedin"):
        contact_parts.append(resume_data["linkedin"])

    if contact_parts:
        p_contact = doc.add_paragraph(" | ".join(contact_parts))
        p_contact.paragraph_format.space_after = Pt(12)
        p_contact.runs[0].font.size = Pt(9)
        p_contact.runs[0].font.color.rgb = RGBColor(0x47, 0x55, 0x69)

    def add_section_header(title: str):
        p_head = doc.add_paragraph()
        p_head.paragraph_format.space_before = Pt(12)
        p_head.paragraph_format.space_after = Pt(4)
        run_head = p_head.add_run(title.upper())
        run_head.font.size = Pt(11.5)
        run_head.font.bold = True
        run_head.font.color.rgb = secondary_color

    # 2. Professional Summary
    summary = resume_data.get("summary")
    if summary:
        add_section_header("Professional Summary")
        p_sum = doc.add_paragraph(summary)
        p_sum.paragraph_format.space_after = Pt(8)

    # 3. Work Experience
    experiences = resume_data.get("experiences", [])
    if experiences:
        add_section_header("Work Experience")
        for exp in experiences:
            p_exp = doc.add_paragraph()
            p_exp.paragraph_format.space_before = Pt(4)
            p_exp.paragraph_format.space_after = Pt(2)
            
            run_title = p_exp.add_run(f"{exp.get('title', 'Role')} ")
            run_title.font.bold = True
            
            company_text = f"| {exp.get('company', '')}" if exp.get('company') else ""
            dates_text = f" ({exp.get('dates', '')})" if exp.get('dates') else ""
            loc_text = f" - {exp.get('location', '')}" if exp.get('location') else ""
            
            run_details = p_exp.add_run(f"{company_text}{dates_text}{loc_text}")
            run_details.font.color.rgb = RGBColor(0x47, 0x55, 0x69)

            bullets = exp.get("bullets", [])
            if isinstance(bullets, str):
                bullets = [b.strip() for b in bullets.split("\n") if b.strip()]

            for bullet in bullets:
                cb = clean_text(bullet)
                if cb and not is_header_duplicate_py(cb):
                    p_bullet = doc.add_paragraph(style='List Bullet')
                    p_bullet.paragraph_format.space_after = Pt(2)
                    p_bullet.paragraph_format.left_indent = Inches(0.25)
                    p_bullet.add_run(cb)

    # 4. Core Skills
    skills = resume_data.get("skills", [])
    if skills:
        add_section_header("Core Competencies & Skills")
        p_skills = doc.add_paragraph()
        p_skills.paragraph_format.space_after = Pt(8)
        p_skills.add_run(" • ".join([clean_text(s) for s in skills if clean_text(s)]))

    # 5. Education
    education = resume_data.get("education", [])
    if education:
        add_section_header("Education & Credentials")
        for edu in education:
            p_edu = doc.add_paragraph()
            p_edu.paragraph_format.space_after = Pt(3)
            run_degree = p_edu.add_run(f"{clean_text(edu.get('degree', 'Degree'))} ")
            run_degree.font.bold = True
            
            inst_text = f"| {clean_text(edu.get('institution', ''))}" if edu.get('institution') else ""
            year_text = f" ({clean_text(edu.get('year', ''))})" if edu.get('year') else ""
            p_edu.add_run(f"{inst_text}{year_text}")

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def generate_pdf(resume_data: Dict[str, Any]) -> bytes:
    """
    Generates a single-column ATS compliant PDF tailored to the selected style format using ReportLab.
    """
    style_id = resume_data.get("style", "classic")

    # Style Palettes for PDF
    pdf_palettes = {
        "classic": {"primary": "#1E293B", "accent": "#475569", "rule": "#CBD5E1"},
        "modern_executive": {"primary": "#1E3A8A", "accent": "#2563EB", "rule": "#93C5FD"},
        "warm_modern": {"primary": "#0D9488", "accent": "#D97706", "rule": "#FDE68A"},
        "minimalist": {"primary": "#0F172A", "accent": "#0284C7", "rule": "#E2E8F0"},
        "leadership": {"primary": "#312E81", "accent": "#4F46E5", "rule": "#C7D2FE"},
        "creative": {"primary": "#064E3B", "accent": "#059669", "rule": "#A7F3D0"}
    }

    palette = pdf_palettes.get(style_id, pdf_palettes["classic"])

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor(palette["primary"]),
        spaceAfter=4
    )

    contact_style = ParagraphStyle(
        'DocContact',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=12,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11.5,
        leading=15,
        textColor=colors.HexColor(palette["accent"]),
        spaceBefore=10,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'DocBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#1E293B'),
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=3
    )

    story = []

    # 1. Header (Name & Contact)
    name_text = clean_text(resume_data.get("name", "CAREER PROFESSIONAL")).upper()
    story.append(Paragraph(name_text, title_style))

    contact_parts = []
    if resume_data.get("phone"):
        contact_parts.append(clean_text(resume_data["phone"]))
    if resume_data.get("email"):
        contact_parts.append(clean_text(resume_data["email"]))
    if resume_data.get("location"):
        contact_parts.append(clean_text(resume_data["location"]))
    if resume_data.get("linkedin"):
        contact_parts.append(clean_text(resume_data["linkedin"]))

    if contact_parts:
        story.append(Paragraph(" | ".join(contact_parts), contact_style))

    def add_pdf_section_header(title: str):
        story.append(Paragraph(title.upper(), section_heading))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor(palette["rule"]), spaceBefore=2, spaceAfter=6))

    # 2. Professional Summary
    summary = clean_text(resume_data.get("summary", ""))
    if summary:
        add_pdf_section_header("Professional Summary")
        story.append(Paragraph(summary, body_style))

    # 3. Work Experience
    experiences = resume_data.get("experiences", [])
    if experiences:
        add_pdf_section_header("Work Experience")
        for exp in experiences:
            exp_title = clean_text(exp.get('title', 'Role'))
            exp_company = clean_text(exp.get('company', ''))
            title_line = f"<b>{exp_title}</b> — <i>{exp_company}</i>"
            dates_loc = []
            if exp.get('dates'):
                dates_loc.append(clean_text(exp['dates']))
            if exp.get('location'):
                dates_loc.append(clean_text(exp['location']))
            
            dates_str = " | ".join(dates_loc)
            if dates_str:
                title_line += f" <font color='#64748B'>({dates_str})</font>"

            story.append(Paragraph(title_line, body_style))

            bullets = exp.get("bullets", [])
            if isinstance(bullets, str):
                bullets = [b.strip() for b in bullets.split("\n") if b.strip()]

            for bullet in bullets:
                cb = clean_text(bullet)
                if cb and not is_header_duplicate_py(cb):
                    # Escape XML entities for ReportLab
                    safe_cb = cb.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                    story.append(Paragraph(f"• {safe_cb}", bullet_style))

            story.append(Spacer(1, 4))

    # 4. Core Skills
    skills = resume_data.get("skills", [])
    if skills:
        add_pdf_section_header("Core Competencies & Skills")
        story.append(Paragraph(" • ".join(skills), body_style))

    # 5. Education
    education = resume_data.get("education", [])
    if education:
        add_pdf_section_header("Education & Credentials")
        for edu in education:
            edu_line = f"<b>{edu.get('degree', 'Degree')}</b> — {edu.get('institution', '')}"
            if edu.get('year'):
                edu_line += f" ({edu['year']})"
            story.append(Paragraph(edu_line, body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
